In [62]:
import glob
import os
import pandas as pd
import numpy as np
import datetime
import warnings
from maks_lib import output_path
from maks_lib import input_path
warnings.simplefilter(action='ignore')
now = datetime.datetime.now()

extension = 'csv'

In [63]:
all_files = glob.glob(output_path+'*.{}'.format(extension))
all_mortage_files  = [file for file in all_files if file.split("\\")[-1].startswith("Cons") and "Mortgage" in file.split("\\")[-1]]
all_deposite_files = [file for file in all_files if file.split("\\")[-1].startswith("Cons") and file not in all_mortage_files]

In [64]:
COLUMN_NAMES = list(pd.read_csv(all_mortage_files[0]).columns)
df_mortgage = pd.DataFrame(columns=COLUMN_NAMES) 
df_deposit = pd.DataFrame(columns=COLUMN_NAMES)

In [65]:
for idx, file in enumerate(all_deposite_files):
    print(file)
    print(pd.read_csv(all_deposite_files[idx]).shape[1])

C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_ALLY_Data_Deposit_03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_CapitalOne_Data_Deposit_03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_CITI_Data_Deposit_03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_PNC_Data_Deposit_03-08-2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_SunTrust_Data_Deposit_03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_Sync_Data_Deposit03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_WellsF_Data_Checking_Acc03_09_2018.csv
14
C:\Users\Deepak.BAN-LBMQ24M2\PycharmProjects\pool-master\data\output\Consolidate_WellsF_Data_Saving_Acc03_09_2018.csv
14

In [66]:
for file in all_deposite_files:
    df_temp =pd.read_csv(file)
    df_temp.columns = ['Date', 'Bank_Name', 'Bank_Product', 'Bank_Product_Type',
       'Bank_Offer_Feature', 'Bank_Product_Name', 'Product_Term', 'Balance',
       'Product_Interest', 'Product_Apy', 'Mortgage_Down_Payment',
       'Mortgage_Loan', 'Min_Credit_Score_Mortagage', 'Mortgage_Apr']
    df_deposit = pd.concat([df_deposit, df_temp])

In [67]:
df_deposit.shape

(244, 14)

In [68]:
df_deposit

,Date,Bank_Name,Bank_Product,Bank_Product_Type,Bank_Offer_Feature,Bank_Product_Name,Product_Term,Balance,Product_Interest,Product_Apy,Mortgage_Down_Payment,Mortgage_Loan,Min_Credit_Score_Mortagage,Mortgage_Apr
0,03-09-2018,ALLY,Deposits,Savings,Online,Online Savings,NaN,NaN,NaN,1.45%,NaN,NaN,NaN,NaN
1,03-09-2018,ALLY,Deposits,Savings,Online,Money Market,NaN,"Less than $5,000 opening deposit",NaN,0.90%,NaN,NaN,NaN,NaN
2,03-09-2018,ALLY,Deposits,Savings,Online,Money Market,NaN,"$5,000 minimum opening deposit",NaN,0.90%,NaN,NaN,NaN,NaN
3,03-09-2018,ALLY,Deposits,Savings,Online,Money Market,NaN,"$25,000 minimum opening deposit",NaN,1.00%,NaN,NaN,NaN,NaN
4,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 month,3.0,"Less than $5,000",NaN,1.00%,NaN,NaN,NaN,NaN
5,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_6 month,6.0,"Less than $5,000",NaN,1.50%,NaN,NaN,NaN,NaN
6,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_9 month,9.0,"Less than $5,000",NaN,1.55%,NaN,NaN,NaN,NaN
7,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_12 month,12.0,"Less than $5,000",NaN,1.75%,NaN,NaN,NaN,NaN
8,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_18 month,18.0,"Less than $5,000",NaN,1.80%,NaN,NaN,NaN,NaN
9,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 year,36.0,"Less than $5,000",NaN,1.85%,NaN,NaN,NaN,NaN
10,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_5 year,60.0,"Less than $5,000",NaN,2.25%,NaN,NaN,NaN,NaN
11,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 month,3.0,"$5,000-$24,999.99",NaN,1.25%,NaN,NaN,NaN,NaN
12,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_6 month,6.0,"$5,000-$24,999.99",NaN,1.60%,NaN,NaN,NaN,NaN
13,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_9 month,9.0,"$5,000-$24,999.99",NaN,1.65%,NaN,NaN,NaN,NaN
14,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_12 month,12.0,"$5,000-$24,999.99",NaN,1.85%,NaN,NaN,NaN,NaN
15,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_18 month,18.0,"$5,000-$24,999.99",NaN,1.95%,NaN,NaN,NaN,NaN
16,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 year,36.0,"$5,000-$24,999.99",NaN,2.00%,NaN,NaN,NaN,NaN
17,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_5 year,60.0,"$5,000-$24,999.99",NaN,2.40%,NaN,NaN,NaN,NaN
18,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 month,3.0,"$25,000 or more",NaN,1.50%,NaN,NaN,NaN,NaN
19,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_6 month,6.0,"$25,000 or more",NaN,1.75%,NaN,NaN,NaN,NaN
20,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_9 month,9.0,"$25,000 or more",NaN,1.80%,NaN,NaN,NaN,NaN
21,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_12 month,12.0,"$25,000 or more",NaN,2.00%,NaN,NaN,NaN,NaN
22,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_18 month,18.0,"$25,000 or more",NaN,2.05%,NaN,NaN,NaN,NaN
23,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_3 year,36.0,"$25,000 or more",NaN,2.10%,NaN,NaN,NaN,NaN
24,03-09-2018,ALLY,Deposits,CD,Online,High Yield CDs_5 year,60.0,"$25,000 or more",NaN,2.50%,NaN,NaN,NaN,NaN
25,03-09-2018,ALLY,Deposits,CD,Online,Raise Your Rate CDs_2 year,24.0,"Less than $5,000",NaN,2.00%,NaN,NaN,NaN,NaN
26,03-09-2018,ALLY,Deposits,CD,Online,Raise Your Rate CDs_4 year,48.0,"Less than $5,000",NaN,2.00%,NaN,NaN,NaN,NaN
27,03-09-2018,ALLY,Deposits,CD,Online,Raise Your Rate CDs_2 year,24.0,"$5,000-$24,999.99",NaN,2.00%,NaN,NaN,NaN,NaN
28,03-09-2018,ALLY,Deposits,CD,Online,Raise Your Rate CDs_4 year,48.0,"$5,000-$24,999.99",NaN,2.00%,NaN,NaN,NaN,NaN
29,03-09-2018,ALLY,Deposits,CD,Online,Raise Your Rate CDs_2 year,24.0,"$25,000 or more",NaN,2.00%,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,03-09-2018,Wells Fargo,Deposits,Checking,Offline,Wells Fargo Everyday Checking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Wells Fargo Way2Save,NaN,$0 or more,0.01%,0.01%,NaN,NaN,NaN,NaN
1,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Platinum Savings - Special Interest,NaN,"$0 - $24,999.99",0.03%,0.03%,NaN,NaN,NaN,NaN
2,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Platinum Savings - Special Interest,NaN,"$25,000 - $99,999.99",1.25%,0.34%,NaN,NaN,NaN,NaN
3,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Platinum Savings - Special Interest,NaN,"$100,000 or more",1.25%,0.35%,NaN,NaN,NaN,NaN
4,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Platinum Savings - Standard Interest,NaN,"$0 - $99,999.99",0.03%,0.03%,NaN,NaN,NaN,NaN
5,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Platinum Savings - Standard Interest,NaN,"$100,000 or more",0.05%,0.05%,NaN,NaN,NaN,NaN
6,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Special CD,9.0,NaN,0.35%,0.35%,NaN,NaN,NaN,NaN
7,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Special CD,19.0,NaN,1.59%,1.60%,NaN,NaN,NaN,NaN
8,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Special CD,39.0,NaN,1.14%,1.15%,NaN,NaN,NaN,NaN
9,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,Special CD,58.0,NaN,1.19%,1.20%,NaN,NaN,NaN,NaN
10,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$0 - $4,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
11,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$5,000 - $9,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
12,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$10,000 - $24,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
13,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$25,000 - $49,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
14,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$50,000 - $99,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
15,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,3.0,"$100,000 +",0.01%,0.01%,NaN,NaN,NaN,NaN
16,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$0 - $4,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
17,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$5,000 - $9,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
18,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$10,000 - $24,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
19,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$25,000 - $49,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
20,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$50,000 - $99,999.99",0.01%,0.01%,NaN,NaN,NaN,NaN
21,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,6.0,"$100,000 +",0.01%,0.01%,NaN,NaN,NaN,NaN
22,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$0 - $4,999.99",0.05%,0.05%,NaN,NaN,NaN,NaN
23,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$5,000 - $9,999.99",0.05%,0.05%,NaN,NaN,NaN,NaN
24,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$10,000 - $24,999.99",0.05%,0.05%,NaN,NaN,NaN,NaN
25,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$25,000 - $49,999.99",0.05%,0.05%,NaN,NaN,NaN,NaN
26,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$50,000 - $99,999.99",0.05%,0.05%,NaN,NaN,NaN,NaN
27,3/9/2018,WELLS FARGO,Deposits,Savings,Offline,CD,12.0,"$100,000 +",0.05%,0.05%,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df_deposit.dropna(axis=0, how='all', inplace=True)

In [70]:
df_deposit.drop(columns=['Mortgage_Down_Payment','Mortgage_Loan', 'Min_Credit_Score_Mortagage', 'Mortgage_Apr'], inplace=True)

In [71]:
df_deposit.rename(columns={"Product_Term": "Term_in_Months","Product_Interest": "Interest","Product_Apy":"APY"}, inplace = True,index=str)

In [72]:
df_deposit['Date'] = now.strftime("%m/%d/%Y")
df_deposit['Bank_Native_Country'] = "US"
df_deposit['State'] = "New York"
df_deposit['Bank_Local_Currency'] = "USD"
df_deposit['Bank_Type'] = "Bank"
df_deposit['Bank_Product'] = "Deposits"
df_deposit['Bank_Product_Code'] = np.NAN
df_deposit['Interest_Type'] = "Variable"
df_deposit['Minm_Balance'] = np.NAN
df_deposit['Maxm_Balance'] = np.NAN

In [73]:
arranged_cols = ['Date', 'Bank_Native_Country','State','Bank_Name','Bank_Local_Currency', 'Bank_Type','Bank_Product','Bank_Product_Type','Bank_Product_Code','Bank_Product_Name','Balance','Minm_Balance','Maxm_Balance','Bank_Offer_Feature','Term_in_Months', 'Interest_Type','Interest', 'APY']

In [74]:
df_deposit = df_deposit.reindex(columns= arranged_cols)

In [75]:
for idx in range(len(df_deposit.index)):
    if "CD" in df_deposit['Bank_Product_Type'].iloc[idx]:
        df_deposit['Interest_Type'].iloc[idx] = "Fixed"

In [76]:
for idx in range(len(df_deposit.index)):
    #print(df_mortgage['Bank_Product_Name'].iloc[idx])
    #print(type(df_mortgage['Bank_Product_Name'].iloc[idx]))
    #  CD  
    
    if "Savings" in df_deposit['Bank_Product_Type'].iloc[idx]:
        s = "SB"
    elif "Checking" in df_deposit['Bank_Product_Type'].iloc[idx]:
        s = "CC"
    else:
        s = "CD"
    try:
        t = int(df_deposit['Term_in_Months'].iloc[idx])
    except ValueError:
        t = "_"        
    df_deposit['Bank_Product_Code'].iloc[idx] = "{0}{1}{2}{3}".format(t,"M", s, df_deposit['Interest_Type'].iloc[idx][0])
    #print(df_mortgage['Interest_Type'].iloc[idx])

In [77]:
df_deposit.head()

,Date,Bank_Native_Country,State,Bank_Name,Bank_Local_Currency,Bank_Type,Bank_Product,Bank_Product_Type,Bank_Product_Code,Bank_Product_Name,Balance,Minm_Balance,Maxm_Balance,Bank_Offer_Feature,Term_in_Months,Interest_Type,Interest,APY
0,03/09/2018,US,New York,ALLY,USD,Bank,Deposits,Savings,_MSBV,Online Savings,NaN,NaN,NaN,Online,NaN,Variable,NaN,1.45%
1,03/09/2018,US,New York,ALLY,USD,Bank,Deposits,Savings,_MSBV,Money Market,"Less than $5,000 opening deposit",NaN,NaN,Online,NaN,Variable,NaN,0.90%
2,03/09/2018,US,New York,ALLY,USD,Bank,Deposits,Savings,_MSBV,Money Market,"$5,000 minimum opening deposit",NaN,NaN,Online,NaN,Variable,NaN,0.90%
3,03/09/2018,US,New York,ALLY,USD,Bank,Deposits,Savings,_MSBV,Money Market,"$25,000 minimum opening deposit",NaN,NaN,Online,NaN,Variable,NaN,1.00%
4,03/09/2018,US,New York,ALLY,USD,Bank,Deposits,CD,3MCDF,High Yield CDs_3 month,"Less than $5,000",NaN,NaN,Online,3.0,Fixed,NaN,1.00%

In [78]:
for idx in range(len(df_deposit.index)):
    if "Below" in str(df_deposit['Balance'].iloc[idx]) or "or less" in str(df_deposit['Balance'].iloc[idx]) or "Less than" in str(df_deposit['Balance'].iloc[idx]) or "less than" in str(df_deposit['Balance'].iloc[idx]) or "Up to" in str(df_deposit['Balance'].iloc[idx]):
        df_deposit['Maxm_Balance'].iloc[idx] = df_deposit['Balance'].iloc[idx]
    elif "-" in str(df_deposit['Balance'].iloc[idx]):
        df_deposit['Minm_Balance'].iloc[idx], df_deposit['Maxm_Balance'].iloc[idx] = str(df_deposit['Balance'].iloc[idx]).split("-")
    elif " to " in str(df_deposit['Balance'].iloc[idx]):
        df_deposit['Minm_Balance'].iloc[idx], df_deposit['Maxm_Balance'].iloc[idx] = str(df_deposit['Balance'].iloc[idx]).split("to")
    else:
        df_deposit['Minm_Balance'].iloc[idx] = df_deposit['Balance'].iloc[idx]

In [79]:
df_deposit.drop(columns=['Balance'], inplace=True)

In [80]:
df_deposit.to_csv(output_path+"US\\" + "US_Deposits_Data_{}.csv".format(now.strftime("%m_%d_%Y")), index=False )